<?php

namespace Database\Seeders;

use App\Models\Customer;
use App\Models\CustomerAddress;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class CustomerSeeder extends Seeder
{
    /**
     * Daftar customer dummy dengan data lengkap.
     */
    private const CUSTOMERS = [
        [
            'customer_code' => 'CUST-000001',
            'full_name' => 'Ahmad Fauzi',
            'account_type' => 'Customer',
            'ktp_number' => '3174010101800001',
            'npwp' => '12.345.678.9-012.000',
            'email' => 'ahmad.fauzi@example.com',
            'phone' => '0812999111222',
            'contact_person' => 'Ahmad Fauzi',
            'company_name' => 'Toko Berkah Jaya',
            'internal_code' => 'TJ-BJ-001',
            'address' => 'Jl. Palmerah Barat No. 12, RT 003 RW 005',
            'province' => 'DKI Jakarta',
            'city' => 'Jakarta Barat',
            'postal_code' => '11480',
            'addresses' => [
                [
                    'label' => 'Toko Utama',
                    'recipient_name' => 'Ahmad Fauzi',
                    'phone' => '0812999111222',
                    'address' => 'Jl. Palmerah Barat No. 12, RT 003 RW 005',
                    'province_code' => '31',
                    'province_name' => 'DKI Jakarta',
                    'regency_code' => '3174',
                    'regency_name' => 'Jakarta Barat',
                    'district_code' => '3174040',
                    'district_name' => 'Palmerah',
                    'village_code' => '3174040001',
                    'village_name' => 'Palmerah',
                    'postal_code' => '11480',
                    'is_active' => true,
                ],
                [
                    'label' => 'Gudang',
                    'recipient_name' => 'Pak Ahmad',
                    'phone' => '0812999111333',
                    'address' => 'Jl. Daan Mogot KM 8 No. 5, Kompleks Pergudangan A3',
                    'province_code' => '31',
                    'province_name' => 'DKI Jakarta',
                    'regency_code' => '3174',
                    'regency_name' => 'Jakarta Barat',
                    'district_code' => '3174050',
                    'district_name' => 'Cengkareng',
                    'village_code' => '3174050002',
                    'village_name' => 'Cengkareng Barat',
                    'postal_code' => '11730',
                    'is_active' => false,
                ],
            ],
        ],
        [
            'customer_code' => 'CUST-000002',
            'full_name' => 'Siti Nurhaliza',
            'account_type' => 'Customer',
            'ktp_number' => '3275011105850002',
            'npwp' => '98.765.432.1-543.000',
            'email' => 'siti.nurhaliza@example.com',
            'phone' => '0857111222333',
            'contact_person' => 'Siti Nurhaliza',
            'company_name' => 'CV Sumber Rezeki',
            'internal_code' => 'CV-SR-002',
            'address' => 'Jl. Margonda Raya No. 88, Ruko Blok B',
            'province' => 'Jawa Barat',
            'city' => 'Depok',
            'postal_code' => '16424',
            'addresses' => [
                [
                    'label' => 'Alamat Utama',
                    'recipient_name' => 'Siti Nurhaliza',
                    'phone' => '0857111222333',
                    'address' => 'Jl. Margonda Raya No. 88, Ruko Blok B',
                    'province_code' => '32',
                    'province_name' => 'Jawa Barat',
                    'regency_code' => '3276',
                    'regency_name' => 'Kota Depok',
                    'district_code' => '3276010',
                    'district_name' => 'Beji',
                    'village_code' => '3276010003',
                    'village_name' => 'Tanah Baru',
                    'postal_code' => '16424',
                    'is_active' => true,
                ],
            ],
        ],
        [
            'customer_code' => 'CUST-000003',
            'full_name' => 'Budi Santoso',
            'account_type' => 'Customer',
            'ktp_number' => '3578010306900003',
            'npwp' => null,
            'email' => 'budi.santoso@example.com',
            'phone' => '0822555666777',
            'contact_person' => 'Budi Santoso',
            'company_name' => 'Toko Murah Meriah',
            'internal_code' => null,
            'address' => 'Jl. Rungkut Industri No. 15',
            'province' => 'Jawa Timur',
            'city' => 'Surabaya',
            'postal_code' => '60293',
            'addresses' => [
                [
                    'label' => 'Alamat Utama',
                    'recipient_name' => 'Budi Santoso',
                    'phone' => '0822555666777',
                    'address' => 'Jl. Rungkut Industri No. 15',
                    'province_code' => '35',
                    'province_name' => 'Jawa Timur',
                    'regency_code' => '3578',
                    'regency_name' => 'Kota Surabaya',
                    'district_code' => '3578040',
                    'district_name' => 'Rungkut',
                    'village_code' => '3578040001',
                    'village_name' => 'Kalirungkut',
                    'postal_code' => '60293',
                    'is_active' => true,
                ],
            ],
        ],
        [
            'customer_code' => 'CUST-000004',
            'full_name' => 'Dewi Lestari',
            'account_type' => 'Customer',
            'ktp_number' => '3372011507950004',
            'npwp' => '55.123.456.7-008.000',
            'email' => 'dewi.lestari@example.com',
            'phone' => '0838777888999',
            'contact_person' => 'Dewi Lestari',
            'company_name' => 'UD Makmur Sentosa',
            'internal_code' => 'UD-MS-004',
            'address' => 'Jl. Slamet Riyadi No. 45',
            'province' => 'Jawa Tengah',
            'city' => 'Solo',
            'postal_code' => '57141',
            'addresses' => [
                [
                    'label' => 'Alamat Utama',
                    'recipient_name' => 'Dewi Lestari',
                    'phone' => '0838777888999',
                    'address' => 'Jl. Slamet Riyadi No. 45',
                    'province_code' => '33',
                    'province_name' => 'Jawa Tengah',
                    'regency_code' => '3372',
                    'regency_name' => 'Kota Surakarta',
                    'district_code' => '3372010',
                    'district_name' => 'Laweyan',
                    'village_code' => '3372010001',
                    'village_name' => 'Penumping',
                    'postal_code' => '57141',
                    'is_active' => true,
                ],
            ],
        ],
        [
            'customer_code' => 'CUST-000005',
            'full_name' => 'PT Global Niaga',
            'account_type' => 'Business',
            'ktp_number' => '3171012512900005',
            'npwp' => '01.234.567.8-091.000',
            'email' => 'info@globalniaga.example.com',
            'phone' => '0215550123',
            'contact_person' => 'Hendra Wijaya',
            'company_name' => 'PT Global Niaga Indonesia',
            'internal_code' => 'GNI-005',
            'address' => 'Jl. Jend. Sudirman Kav 52-53, Gedung Bursa Efek Lt. 5',
            'province' => 'DKI Jakarta',
            'city' => 'Jakarta Selatan',
            'postal_code' => '12190',
            'addresses' => [
                [
                    'label' => 'Kantor Pusat',
                    'recipient_name' => 'Hendra Wijaya',
                    'phone' => '0215550123',
                    'address' => 'Jl. Jend. Sudirman Kav 52-53, Gedung Bursa Efek Lt. 5',
                    'province_code' => '31',
                    'province_name' => 'DKI Jakarta',
                    'regency_code' => '3174',
                    'regency_name' => 'Jakarta Selatan',
                    'district_code' => '3174060',
                    'district_name' => 'Setiabudi',
                    'village_code' => '3174060002',
                    'village_name' => 'Karet',
                    'postal_code' => '12190',
                    'is_active' => true,
                ],
                [
                    'label' => 'Gudang Pusat',
                    'recipient_name' => 'Bagian Logistik',
                    'phone' => '0215550456',
                    'address' => 'Jl. Raya Bekasi KM 23, Kawasan Industri Pulogadung Blok F',
                    'province_code' => '31',
                    'province_name' => 'DKI Jakarta',
                    'regency_code' => '3175',
                    'regency_name' => 'Jakarta Timur',
                    'district_code' => '3175080',
                    'district_name' => 'Cakung',
                    'village_code' => '3175080003',
                    'village_name' => 'Pulogadung',
                    'postal_code' => '13920',
                    'is_active' => false,
                ],
                [
                    'label' => 'Cabang Bandung',
                    'recipient_name' => 'Rina Marlina',
                    'phone' => '0227001234',
                    'address' => 'Jl. Asia Afrika No. 100, Ruko Bandung Trade Center Blok A-5',
                    'province_code' => '32',
                    'province_name' => 'Jawa Barat',
                    'regency_code' => '3273',
                    'regency_name' => 'Kota Bandung',
                    'district_code' => '3273140',
                    'district_name' => 'Regol',
                    'village_code' => '3273140001',
                    'village_name' => 'Cigereleng',
                    'postal_code' => '40253',
                    'is_active' => false,
                ],
            ],
        ],
        [
            'customer_code' => 'CUST-000006',
            'full_name' => 'Rudi Hartono',
            'account_type' => 'Customer',
            'ktp_number' => '1271010108890006',
            'npwp' => null,
            'email' => 'rudi.hartono@example.com',
            'phone' => '0866111222333',
            'contact_person' => 'Rudi Hartono',
            'company_name' => null,
            'internal_code' => null,
            'address' => 'Jl. Setiabudi No. 20',
            'province' => 'Jawa Barat',
            'city' => 'Bandung',
            'postal_code' => '40141',
            'addresses' => [
                [
                    'label' => 'Rumah',
                    'recipient_name' => 'Rudi Hartono',
                    'phone' => '0866111222333',
                    'address' => 'Jl. Setiabudi No. 20, RT 004 RW 002',
                    'province_code' => '32',
                    'province_name' => 'Jawa Barat',
                    'regency_code' => '3273',
                    'regency_name' => 'Kota Bandung',
                    'district_code' => '3273070',
                    'district_name' => 'Cidadap',
                    'village_code' => '3273070001',
                    'village_name' => 'Hegarmanah',
                    'postal_code' => '40141',
                    'is_active' => true,
                ],
            ],
        ],
        [
            'customer_code' => 'CUST-000007',
            'full_name' => 'Linda Kusuma',
            'account_type' => 'Customer',
            'ktp_number' => '1271022001920007',
            'npwp' => '77.888.999.0-123.000',
            'email' => 'linda.kusuma@example.com',
            'phone' => '0813111777888',
            'contact_person' => 'Linda Kusuma',
            'company_name' => 'Toko Serba Ada Linda',
            'internal_code' => 'TSA-007',
            'address' => 'Jl. Tunjungan No. 30, Ruko Blok A',
            'province' => 'Jawa Timur',
            'city' => 'Surabaya',
            'postal_code' => '60275',
            'addresses' => [
                [
                    'label' => 'Alamat Utama',
                    'recipient_name' => 'Linda Kusuma',
                    'phone' => '0813111777888',
                    'address' => 'Jl. Tunjungan No. 30, Ruko Blok A',
                    'province_code' => '35',
                    'province_name' => 'Jawa Timur',
                    'regency_code' => '3578',
                    'regency_name' => 'Kota Surabaya',
                    'district_code' => '3578020',
                    'district_name' => 'Genteng',
                    'village_code' => '3578020001',
                    'village_name' => 'Genteng',
                    'postal_code' => '60275',
                    'is_active' => true,
                ],
                [
                    'label' => 'Rumah',
                    'recipient_name' => 'Linda Kusuma',
                    'phone' => '0813111555999',
                    'address' => 'Perumahan Citraland Blok G No. 12',
                    'province_code' => '35',
                    'province_name' => 'Jawa Timur',
                    'regency_code' => '3578',
                    'regency_name' => 'Kota Surabaya',
                    'district_code' => '3578070',
                    'district_name' => 'Lakarsantri',
                    'village_code' => '3578070002',
                    'village_name' => 'Jeruk',
                    'postal_code' => '60219',
                    'is_active' => false,
                ],
            ],
        ],
        [
            'customer_code' => 'CUST-000008',
            'full_name' => 'Irfan Hakim',
            'account_type' => 'Customer',
            'ktp_number' => '3372011206930008',
            'npwp' => null,
            'email' => 'irfan.hakim@example.com',
            'phone' => '0822777111222',
            'contact_person' => 'Irfan Hakim',
            'company_name' => null,
            'internal_code' => null,
            'address' => 'Jl. Parangtritis No. 55',
            'province' => 'DI Yogyakarta',
            'city' => 'Yogyakarta',
            'postal_code' => '55142',
            'addresses' => [
                [
                    'label' => 'Alamat Utama',
                    'recipient_name' => 'Irfan Hakim',
                    'phone' => '0822777111222',
                    'address' => 'Jl. Parangtritis No. 55',
                    'province_code' => '34',
                    'province_name' => 'DI Yogyakarta',
                    'regency_code' => '3402',
                    'regency_name' => 'Kabupaten Bantul',
                    'district_code' => '3402040',
                    'district_name' => 'Sewon',
                    'village_code' => '3402040001',
                    'village_name' => 'Pendowoharjo',
                    'postal_code' => '55142',
                    'is_active' => true,
                ],
            ],
        ],
        [
            'customer_code' => 'CUST-000009',
            'full_name' => 'PT Cahaya Abadi',
            'account_type' => 'Business',
            'ktp_number' => '3275011508900009',
            'npwp' => '31.415.926.5-008.000',
            'email' => 'purchasing@cahayaabadi.example.com',
            'phone' => '0218882345',
            'contact_person' => 'Slamet Riyadi',
            'company_name' => 'PT Cahaya Abadi Perkasa',
            'internal_code' => 'CAP-009',
            'address' => 'Jl. Pantai Indah Kapuk Raya No. 10, Ruko Cordoba Blok C',
            'province' => 'DKI Jakarta',
            'city' => 'Jakarta Utara',
            'postal_code' => '14470',
            'addresses' => [
                [
                    'label' => 'Kantor',
                    'recipient_name' => 'Slamet Riyadi',
                    'phone' => '0218882345',
                    'address' => 'Jl. Pantai Indah Kapuk Raya No. 10, Ruko Cordoba Blok C',
                    'province_code' => '31',
                    'province_name' => 'DKI Jakarta',
                    'regency_code' => '3172',
                    'regency_name' => 'Jakarta Utara',
                    'district_code' => '3172060',
                    'district_name' => 'Penjaringan',
                    'village_code' => '3172060003',
                    'village_name' => 'Kapuk Muara',
                    'postal_code' => '14470',
                    'is_active' => true,
                ],
            ],
        ],
        [
            'customer_code' => 'CUST-000010',
            'full_name' => 'Ratna Dewi',
            'account_type' => 'Customer',
            'ktp_number' => '3371011601940010',
            'npwp' => null,
            'email' => 'ratna.dewi@example.com',
            'phone' => '0856333444555',
            'contact_person' => 'Ratna Dewi',
            'company_name' => 'Warung Kelontong Ratna',
            'internal_code' => null,
            'address' => 'Jl. Kaliurang KM 5 No. 10',
            'province' => 'DI Yogyakarta',
            'city' => 'Sleman',
            'postal_code' => '55281',
            'addresses' => [
                [
                    'label' => 'Alamat Utama',
                    'recipient_name' => 'Ratna Dewi',
                    'phone' => '0856333444555',
                    'address' => 'Jl. Kaliurang KM 5 No. 10',
                    'province_code' => '34',
                    'province_name' => 'DI Yogyakarta',
                    'regency_code' => '3404',
                    'regency_name' => 'Kabupaten Sleman',
                    'district_code' => '3404080',
                    'district_name' => 'Ngaglik',
                    'village_code' => '3404080002',
                    'village_name' => 'Sariharjo',
                    'postal_code' => '55281',
                    'is_active' => true,
                ],
            ],
        ],
    ];

    public function run(): void
    {
        $sales = User::query()->where('email', 'sales@example.com')->first();

        if (! $sales) {
            $this->command?->warn('Sales demo user not found. Run AdminUserSeeder first.');

            return;
        }

        $this->command?->info('Seeding customers with addresses...');

        foreach (self::CUSTOMERS as $data) {
            $addressData = $data['addresses'] ?? [];
            unset($data['addresses']);

            $data['status'] = 'active';
            $data['password'] = Hash::make('password123');
            $data['sales_id'] = $sales->id;

            $customer = Customer::query()->updateOrCreate(
                ['email' => $data['email']],
                $data,
            );

            foreach ($addressData as $addr) {
                CustomerAddress::query()->updateOrCreate(
                    [
                        'customer_id' => $customer->id,
                        'label' => $addr['label'],
                    ],
                    array_merge($addr, ['customer_id' => $customer->id]),
                );
            }

            $this->command?->line("  ✓ {$customer->full_name} — {$customer->company_name}");
        }

        $this->command?->info('Customer seeding complete!');
    }
}
